export const EMPTY_BLOCK = 0;

export const WorldMapBlock = Object.freeze({
  Grass: 1,
  Dirt: 2,
  Stone: 3,
  DeepStone: 4,
  Sand: 5,
  Gravel: 6,
  Clay: 7,
  Mud: 8,
  DryDirt: 9,
  SaltFlat: 10,
  Snow: 11,
  Ice: 12,
  FrozenSoil: 13,
  Basalt: 14,
  Ash: 15,
  Bedrock: 16,
  Water: 17,
  SwampWater: 18,
  ToxicWater: 19,
  Lava: 20,
  Quicksand: 21,
  Trunk: 22,
  Leaves: 23,
  PineTrunk: 24,
  PineLeaves: 25,
  DeadWood: 26,
  GiantRoot: 27,
  GrassPlant: 28,
  DryGrass: 29,
  Bush: 30,
  DeadBush: 31,
  Cactus: 32,
  Reed: 33,
  SwampGrass: 34,
  SnowBush: 35,
  Thorn: 36,
  Moss: 37,
  Lichen: 38,
  Vine: 39,
  GlowMycelium: 40,
  Mushroom: 41,
  Seaweed: 42,
  AquaticPlant: 43,
  Coral: 44,
  DeadCoral: 45,
  ShellBed: 46,
  Coal: 47,
});

export const RESOURCE_ID = Object.freeze({
  none: 0,
  grassFiber: 1,
  soil: 2,
  stone: 3,
  sand: 4,
  clay: 5,
  snow: 6,
  basalt: 7,
  water: 8,
  wood: 9,
  leaves: 10,
  coal: 11,
  salt: 12,
  ice: 13,
  lava: 14,
  organic: 15,
  cactus: 16,
  reed: 17,
  moss: 18,
  mushroom: 19,
  aquaticPlant: 20,
  coral: 21,
  shell: 22,
});

export const BiomeType = Object.freeze({
  Plains: 1,
  Forest: 2,
  Rainforest: 3,
  Desert: 4,
  Wetland: 5,
  Swamp: 6,
  Snowfield: 7,
  Tundra: 8,
  Mountain: 9,
  Volcano: 10,
  Ocean: 11,
  Beach: 12,
  River: 13,
  Lake: 14,
  Cave: 15,
  DeepCave: 16,
});

export const WORLD_MAP_BLOCK_DEBUG_COLOR = Object.freeze({
  [WorldMapBlock.Grass]: "#4f9a3d",
  [WorldMapBlock.Dirt]: "#7a5230",
  [WorldMapBlock.Stone]: "#777777",
  [WorldMapBlock.DeepStone]: "#3f3f46",
  [WorldMapBlock.Sand]: "#d8c174",
  [WorldMapBlock.Gravel]: "#8a8579",
  [WorldMapBlock.Clay]: "#a77d64",
  [WorldMapBlock.Mud]: "#4f3828",
  [WorldMapBlock.DryDirt]: "#9b6a3c",
  [WorldMapBlock.SaltFlat]: "#e6e2cf",
  [WorldMapBlock.Snow]: "#eef6ff",
  [WorldMapBlock.Ice]: "#a9d8ff",
  [WorldMapBlock.FrozenSoil]: "#8c9aa3",
  [WorldMapBlock.Basalt]: "#2f3033",
  [WorldMapBlock.Ash]: "#6d6a66",
  [WorldMapBlock.Bedrock]: "#1e1e24",
  [WorldMapBlock.Water]: "#2f7ed8",
  [WorldMapBlock.SwampWater]: "#3d5f45",
  [WorldMapBlock.ToxicWater]: "#72c442",
  [WorldMapBlock.Lava]: "#ff5a1f",
  [WorldMapBlock.Quicksand]: "#b99b55",
  [WorldMapBlock.Trunk]: "#6b3f22",
  [WorldMapBlock.Leaves]: "#2f7d32",
  [WorldMapBlock.PineTrunk]: "#5a3a25",
  [WorldMapBlock.PineLeaves]: "#1f5f3a",
  [WorldMapBlock.DeadWood]: "#4a3a2a",
  [WorldMapBlock.GiantRoot]: "#5b351f",
  [WorldMapBlock.GrassPlant]: "#65b84a",
  [WorldMapBlock.DryGrass]: "#c2a44e",
  [WorldMapBlock.Bush]: "#3d8b3d",
  [WorldMapBlock.DeadBush]: "#8b6a3e",
  [WorldMapBlock.Cactus]: "#2f9b57",
  [WorldMapBlock.Reed]: "#8ba94e",
  [WorldMapBlock.SwampGrass]: "#4f7f3c",
  [WorldMapBlock.SnowBush]: "#c9d8d2",
  [WorldMapBlock.Thorn]: "#5d4a34",
  [WorldMapBlock.Moss]: "#3f8f4a",
  [WorldMapBlock.Lichen]: "#9ca66b",
  [WorldMapBlock.Vine]: "#2f7a35",
  [WorldMapBlock.GlowMycelium]: "#6ef0c2",
  [WorldMapBlock.Mushroom]: "#b85b5b",
  [WorldMapBlock.Seaweed]: "#227c5c",
  [WorldMapBlock.AquaticPlant]: "#3fa878",
  [WorldMapBlock.Coral]: "#ff7f7f",
  [WorldMapBlock.DeadCoral]: "#9a8f86",
  [WorldMapBlock.ShellBed]: "#e4d6b5",
  [WorldMapBlock.Coal]: "#1b1a1d",
});

export const WORLD_MAP_BLOCK_RENDER_TYPE = Object.freeze({
  [WorldMapBlock.Grass]: "grass",
  [WorldMapBlock.Dirt]: "dirt",
  [WorldMapBlock.Stone]: "stone",
  [WorldMapBlock.DeepStone]: "deepStone",
  [WorldMapBlock.Sand]: "sand",
  [WorldMapBlock.Gravel]: "gravel",
  [WorldMapBlock.Clay]: "clay",
  [WorldMapBlock.Mud]: "mud",
  [WorldMapBlock.DryDirt]: "dryDirt",
  [WorldMapBlock.SaltFlat]: "saltFlat",
  [WorldMapBlock.Snow]: "snow",
  [WorldMapBlock.Ice]: "ice",
  [WorldMapBlock.FrozenSoil]: "frozenSoil",
  [WorldMapBlock.Basalt]: "basalt",
  [WorldMapBlock.Ash]: "ash",
  [WorldMapBlock.Bedrock]: "bedrock",
  [WorldMapBlock.Water]: "water",
  [WorldMapBlock.SwampWater]: "swampWater",
  [WorldMapBlock.ToxicWater]: "toxicWater",
  [WorldMapBlock.Lava]: "lava",
  [WorldMapBlock.Quicksand]: "quicksand",
  [WorldMapBlock.Trunk]: "trunk",
  [WorldMapBlock.Leaves]: "leaves",
  [WorldMapBlock.PineTrunk]: "pineTrunk",
  [WorldMapBlock.PineLeaves]: "pineLeaves",
  [WorldMapBlock.DeadWood]: "deadWood",
  [WorldMapBlock.GiantRoot]: "giantRoot",
  [WorldMapBlock.GrassPlant]: "grassPlant",
  [WorldMapBlock.DryGrass]: "dryGrass",
  [WorldMapBlock.Bush]: "bush",
  [WorldMapBlock.DeadBush]: "deadBush",
  [WorldMapBlock.Cactus]: "cactus",
  [WorldMapBlock.Reed]: "reed",
  [WorldMapBlock.SwampGrass]: "swampGrass",
  [WorldMapBlock.SnowBush]: "snowBush",
  [WorldMapBlock.Thorn]: "thorn",
  [WorldMapBlock.Moss]: "moss",
  [WorldMapBlock.Lichen]: "lichen",
  [WorldMapBlock.Vine]: "vine",
  [WorldMapBlock.GlowMycelium]: "glowMycelium",
  [WorldMapBlock.Mushroom]: "mushroom",
  [WorldMapBlock.Seaweed]: "seaweed",
  [WorldMapBlock.AquaticPlant]: "aquaticPlant",
  [WorldMapBlock.Coral]: "coral",
  [WorldMapBlock.DeadCoral]: "deadCoral",
  [WorldMapBlock.ShellBed]: "shellBed",
  [WorldMapBlock.Coal]: "coal",
});

export const WORLD_MAP_BLOCK_RESOURCE_ID = Object.freeze({
  [EMPTY_BLOCK]: RESOURCE_ID.none,
  [WorldMapBlock.Grass]: RESOURCE_ID.grassFiber,
  [WorldMapBlock.Dirt]: RESOURCE_ID.soil,
  [WorldMapBlock.Stone]: RESOURCE_ID.stone,
  [WorldMapBlock.DeepStone]: RESOURCE_ID.stone,
  [WorldMapBlock.Sand]: RESOURCE_ID.sand,
  [WorldMapBlock.Gravel]: RESOURCE_ID.stone,
  [WorldMapBlock.Clay]: RESOURCE_ID.clay,
  [WorldMapBlock.Mud]: RESOURCE_ID.soil,
  [WorldMapBlock.DryDirt]: RESOURCE_ID.soil,
  [WorldMapBlock.SaltFlat]: RESOURCE_ID.salt,
  [WorldMapBlock.Snow]: RESOURCE_ID.snow,
  [WorldMapBlock.Ice]: RESOURCE_ID.ice,
  [WorldMapBlock.FrozenSoil]: RESOURCE_ID.soil,
  [WorldMapBlock.Basalt]: RESOURCE_ID.basalt,
  [WorldMapBlock.Ash]: RESOURCE_ID.soil,
  [WorldMapBlock.Bedrock]: RESOURCE_ID.none,
  [WorldMapBlock.Water]: RESOURCE_ID.water,
  [WorldMapBlock.SwampWater]: RESOURCE_ID.water,
  [WorldMapBlock.ToxicWater]: RESOURCE_ID.water,
  [WorldMapBlock.Lava]: RESOURCE_ID.lava,
  [WorldMapBlock.Quicksand]: RESOURCE_ID.sand,
  [WorldMapBlock.Trunk]: RESOURCE_ID.wood,
  [WorldMapBlock.Leaves]: RESOURCE_ID.leaves,
  [WorldMapBlock.PineTrunk]: RESOURCE_ID.wood,
  [WorldMapBlock.PineLeaves]: RESOURCE_ID.leaves,
  [WorldMapBlock.DeadWood]: RESOURCE_ID.wood,
  [WorldMapBlock.GiantRoot]: RESOURCE_ID.wood,
  [WorldMapBlock.GrassPlant]: RESOURCE_ID.grassFiber,
  [WorldMapBlock.DryGrass]: RESOURCE_ID.grassFiber,
  [WorldMapBlock.Bush]: RESOURCE_ID.leaves,
  [WorldMapBlock.DeadBush]: RESOURCE_ID.organic,
  [WorldMapBlock.Cactus]: RESOURCE_ID.cactus,
  [WorldMapBlock.Reed]: RESOURCE_ID.reed,
  [WorldMapBlock.SwampGrass]: RESOURCE_ID.grassFiber,
  [WorldMapBlock.SnowBush]: RESOURCE_ID.leaves,
  [WorldMapBlock.Thorn]: RESOURCE_ID.organic,
  [WorldMapBlock.Moss]: RESOURCE_ID.none,
  [WorldMapBlock.Lichen]: RESOURCE_ID.moss,
  [WorldMapBlock.Vine]: RESOURCE_ID.organic,
  [WorldMapBlock.GlowMycelium]: RESOURCE_ID.mushroom,
  [WorldMapBlock.Mushroom]: RESOURCE_ID.mushroom,
  [WorldMapBlock.Seaweed]: RESOURCE_ID.aquaticPlant,
  [WorldMapBlock.AquaticPlant]: RESOURCE_ID.aquaticPlant,
  [WorldMapBlock.Coral]: RESOURCE_ID.coral,
  [WorldMapBlock.DeadCoral]: RESOURCE_ID.coral,
  [WorldMapBlock.ShellBed]: RESOURCE_ID.shell,
  [WorldMapBlock.Coal]: RESOURCE_ID.coal,
});

export function renderTypeForBlock(block) {
  return WORLD_MAP_BLOCK_RENDER_TYPE[block] ?? null;
}

export function resourceIdForBlock(block) {
  return WORLD_MAP_BLOCK_RESOURCE_ID[Number(block)] ?? RESOURCE_ID.none;
}

export function debugColorForBlock(block) {
  return WORLD_MAP_BLOCK_DEBUG_COLOR[block] ?? "#4f9a3d";
}
